### ISSUE TITLE
Including a ref to this project makes certain other files dissapear

### ISSUE THREAD

**Issue by bradphelan** [aienabled/WpfNetStandardSample#3]
I have the following code in my project file

```
  <PropertyGroup Label="MultilingualAppToolkit">
    <MultilingualAppToolkitVersion>4.0</MultilingualAppToolkitVersion>
    <MultilingualFallbackLanguage>en</MultilingualFallbackLanguage>
  </PropertyGroup>
  <ItemGroup>
    <XliffResource Include="**\*.xlf" />
  </ItemGroup>
```

without a reference to the WPF support supplied in this library it works. With a reference none of the **xlf** files show up in the solution browser. 

Any idea why that may be?

**Comment by bradphelan** [comment]
There seems to be a big file 

https://github.com/aienabled/WpfNetStandardSample/blob/master/CustomProjectSystem/Rules/ProjectItemsSchema.xaml

that is missing xlf as an extensions. I'm not really sure how this is meant to work. Adding stuff to this file feels like the wrong thing to be doing?

**Comment by aienabled** [comment]
@bradphelan, you need to add `xlf` file extension and ContentType for `XliffResource` there... quite similar to XAML page. Not sure if you will need to create a separate "XAML rule" (a special XAML file with a definition for `XliffResource`).
Usually `XliffResource` is already defined somewhere, you just need to find where and copy its definition.
I've created this file mostly by looking into default ProjectItemsSchema.xaml somewhere inside `C:\Program Files (x86)\Microsoft Visual Studio` or `C:\Program Files (x86)\MSBuild`.

**Comment by bradphelan** [comment]
Why does it override stuff that is already defined? The ``<XLiffResource>`` tag for projects is enabled by the [multi lingual app toolkit VSIX plugin](https://visualstudiogallery.msdn.microsoft.com/652031cd-b2bd-44e7-a3e9-0ad6c5333310) Perhaps there is a way not to clobber it.

**Comment by bradphelan** [comment]
I've found all the schema stuff in 

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Multilingual App Toolkit\v4.0

There's a couple of xaml files in there

[xamlfiles.zip](https://github.com/aienabled/WpfNetStandardSample/files/1368064/xamlfiles.zip)

plus tons of .targets files and dlls.

What is the exact cause of the problem here. Why did you have to create the large file you did rather than just add the rules for XAML. I'm assuming there is a good reason and I'm just trying to understand.

**Comment by bradphelan** [comment]
I've added 
![image](https://user-images.githubusercontent.com/17650/31333179-53c8dfde-ace9-11e7-8ccf-eb7b0360da40.png)
and
![image](https://user-images.githubusercontent.com/17650/31333206-6d6e3fe2-ace9-11e7-8914-a258d9ef24e1.png)

but it still doesn't show the xlf files. Restarted Visual Studio of course

**Comment by aienabled** [comment]
@bradphelan I can only guess that you need to import these targets from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\Multilingual App Toolkit\v4.0 (before or after custom targets).

**Comment by bradphelan** [comment]
ok. I can try that. But I'd like to understand why it was necessary to redefine all the standard stuff and in the process erase anything a plugin has registered rather than just add XAML/WPF support. What is the key idea I'm missing here?

**Comment by aienabled** [comment]
@bradphelan I don't have complete understanding too.
But from what I learned in the past 1.5 years since adapting https://github.com/Microsoft/VSProjectSystem (and https://github.com/dotnet/project-system previously known as New or Roslyn project system, this project is built upon it) is that it doesn't include many things (like XAML file definitions) so we have to define them. Time passed and I didn't really monitored the whole situation, so perhaps there are some improvements and most of the Rules (located at https://github.com/aienabled/WpfNetStandardSample/blob/master/CustomProjectSystem/Rules) could be safely removed as they already should be defined by https://github.com/dotnet/project-system
Some plugins relied on old project system support (and I'm not sure how file type mapping worked then - was it using XAML Rules or something else) and might not work with new project system. But in the case of Multilingual App Toolkit it seems straightforward that you need to import its targets into your project (or directly into your custom targets so all projects importing custom targets will also import Multilingual App Toolkit targets) as they define the XAML Rules.

**Comment by bradphelan** [comment]
I still don't quite get it. If I don't reference your ``CustomProject.props`` file then the multi language toolkit **is included**. This means the default SDK 461 project system already includes the reference to the correct targets files from the plugin. However as soon as I do reference your ``CustomProjects.props`` it no longer works. So this means you are not just adding things, you are removing things as well.  I hope there is a way to extend rather than replace the current state.

**Comment by aienabled** [comment]
@bradphelan, oh, I see. I don't intentionally exclude anything other than these two properties in `CustomProject.props`:
```XML
<EnableDefaultItems>false</EnableDefaultItems>
<EnableDefaultCompileItems>false</EnableDefaultCompileItems>		
```

**Comment by aienabled** [comment]
It seems importing custom `ProjectSchemaDefinitions` (I mean `ProjectItemsSchema.xml`) will not override everything already defined by new Project System (from ProjectSDK). It's additive. I just pushed this commit https://github.com/aienabled/WpfNetStandardSample/commit/fc2d761d48e23c94bf806a7c77e3a7f2ec778606 I'm quite sure there are a lot of things which can be removed from Rules folder now as they're already implemented by new Project System.

**Comment by bradphelan** [comment]
The reason is here

<?xml version="1.0"	encoding="utf-8"?>
```

<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<PropertyGroup>		
		<TargetFramework>net462</TargetFramework>
		<EnableDefaultItems>false</EnableDefaultItems>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>		
	</PropertyGroup>
		
	<Import Project="$(MSBuildThisFileDirectory)\CustomProject.targets" />
	
</Project>
```

**EnableDefaultItems** and **EnableDefaultCompileItems** have been set to false. This wipes out the built in rules. Setting them to true causes errors with the XAML compile being that duplicate compile rules have been added for the same files. But I think this should be fixible ( I hope ) Will go have some lunch and get back to this in an hour or so.

**Comment by aienabled** [comment]
@bradphelan, that's what I wrote above. It's nice you caught it now.
Perhaps we can get rid of them. I will take a look now.

**Comment by aienabled** [comment]
@bradphelan, great news, I've removed all the extra rules and simplified default items inclusion entry.
See commit https://github.com/aienabled/WpfNetStandardSample/commit/52a009992e9ba6e98ae104f892c5831cf1bb79d7 (you can simply take `CustomProjectSystem` folder and replace yours (if you haven't done any changes), other than that I didn't change anything).

It seems that the issue https://github.com/aienabled/WpfNetStandardSample/issues/1 is also resolved now - I can't reproduce it anymore.

**Comment by bradphelan** [comment]
Ok I'll give it a spin 👍

**Comment by bradphelan** [comment]
It works perfectly. Thanks for the fast turn around on this 🥇   

But #1 is still a problem for me

![image](https://user-images.githubusercontent.com/17650/31337002-ac78e59c-acf9-11e7-846f-424fa9985d08.png)

**Comment by aienabled** [comment]
@bradphelan, I'm glad to help. Closing this now.
Regarding #1, you're right. It seems ReSharper fooled me again.
From the build log it's obvious that when `*.tmp_proj` (which is related to two-step XAML build process, not something I wrote) is starting building all the previous errors are cleaned and don't appear in the Errors menu, only errors which happened after starting building tmp project displayed there.

Regards!
